In [2]:
import pandas as pd
extract_csv = pd.read_csv("experiment_data_final.csv")
extract_csv.head(100)

program_name  threads  width l1_cache l2_cache l3_cache  \
0       raytrace        8      4      64k       1m      16m   
1       raytrace        8      4      32k       1m      16m   
2       raytrace        8      4      32k       2m      32m   
3       raytrace        8      4      64k       2m      32m   
4      swaptions        8      4      64k       1m      32m   
5      swaptions        8      4      32k       2m      32m   
6      swaptions        8      4      64k       2m      32m   
7      swaptions        8      8      32k       2m      32m   
8      swaptions        8      4      32k       1m      32m   
9      swaptions        8      4      64k       1m      16m   
10     swaptions        8      4      32k       2m      16m   
11     swaptions        8      4      64k       2m      16m   
12     swaptions        8      4      32k       1m      16m   
13  blackscholes        8      4      32k       2m      16m   
14  blackscholes        8      8      32k       1m      16m   
15  blackscholes        8      4      64k       1m      16m   
16  blackscholes        8      8      64k       2m      16m   
17  blackscholes        8      4      32k       1m      16m   
18  blackscholes        8      8      32k       2m      16m   
19  blackscholes        8      4      64k       2m      16m   
20  blackscholes        8      8      64k       1m      16m   
21  blackscholes        8      4      32k       2m      32m   
22  blackscholes        8      8      32k       1m      32m   
23  blackscholes        8      4      64k       1m      32m   
24  blackscholes        8      8      64k       2m      32m   
25  blackscholes        8      4      32k       1m      32m   
26  blackscholes        8      8      32k       2m      32m   
27  blackscholes        8      4      64k       2m      32m   
28  blackscholes        8      8      64k       1m      32m   
29       canneal        8      4      64k       1m      16m   
30       canneal        8      4      32k       1m      16m   
31       canneal        8      4      64k       1m      32m   
32       canneal        8      4      32k       2m      32m   
33       canneal        8      4      64k       2m      32m   
34       canneal        8      4      32k       1m      32m   
35  fluidanimate        8      4      32k       1m      16m   
36  fluidanimate        8      4      64k       2m      32m   
37  fluidanimate        8      4      32k       2m      32m   

    committed_instructions_per_cycle  branch_prediction_accuracy  \
0                                NaN                         NaN   
1                                NaN                         NaN   
2                                NaN                         NaN   
3                                NaN                         NaN   
4                             2.2680                      0.8384   
5                             2.0280                      0.8384   
6                             2.2730                      0.8385   
7                                NaN                         NaN   
8                             2.0280                      0.8384   
9                             2.2680                      0.8384   
10                            2.0280                      0.8384   
11                            2.2730                      0.8385   
12                            2.0280                      0.8384   
13                            0.8705                      0.9600   
14                            0.9914                      0.9604   
15                            0.8712                      0.9601   
16                            0.9923                      0.9604   
17                            0.8705                      0.9600   
18                            0.9914                      0.9604   
19                            0.8712                      0.9600   
20                            0.9922                      0.9604   
21                            0.8705              

In [3]:
import numpy as np

In [4]:
#Make column 'width' a string
extract_csv['width'] = extract_csv['width'].apply(str)

In [5]:
extract_csv_numerical = extract_csv.select_dtypes(include=[np.number])
extract_csv_numerical.head()

threads  committed_instructions_per_cycle  branch_prediction_accuracy  \
0        8                               NaN                         NaN   
1        8                               NaN                         NaN   
2        8                               NaN                         NaN   
3        8                               NaN                         NaN   
4        8                             2.268                      0.8384   

   instructions  accesses_mod_shared_mm  accesses_mod_shared_l3  \
0           NaN                  153172                  360192   
1           NaN                  604276                 1471215   
2           NaN                 2249433                 5288573   
3           NaN                 1464840                 3399469   
4  5.034279e+09                   10710                   12562   

   hits_mod_shared_l3  misses_mod_shared_l3  reads_mod_shared_l3  \
0                8149                352043                70404   
1               29999               1441216               289889   
2               26549               5262024               935710   
3               23032               3376437               609675   
4                1689                 10873                 5301   

   writes_mod_shared_l3  hw_threads       cycles  dispatch_ipc  issue_ipc  \
0                 90917          16   5162965136        0.7986     0.7507   
1                344386          16  13815380707        0.7792     0.7278   
2               1340272          16  31009448393        0.7810     0.6824   
3                878197          16  24088271698        0.7896     0.7000   
4                  7098          16   1527718090        4.8170     4.6460   

   commit_total  commit_ipc  commit_pred_acc  issue_commit_totals_diff  \
0    3601320852      0.6975           0.9427                 274396619   
1    9334925693      0.6757           0.9411                 719915356   
2   19379657571      0.6250           0.9194                1781152056   
3   15494060522      0.6432           0.9236                1368437026   
4    7028781289      4.6010           0.8384                  69165568   

   dispatch_issue_totals_diff  
0                   247322180  
1                   710294321  
2                  3058017744  
3                  2156605493  
4                   260383915

In [6]:
def eda_numerical(input_data):
    features = list(input_data)
    dict_output_data = {"variable":[],
                        "number_nan":[],
                        "number_distinct":[],
                        "mean":[],
                        "max":[],
                        "min":[],
                        "std":[],
                        "perc25":[],
                        "perc50":[],
                        "perc75":[]
                       }
    for feature in features:
        dict_output_data["variable"].append(feature)
        dict_output_data["number_nan"].append(input_data[feature].isna().sum())
        dict_output_data["number_distinct"].append(input_data[feature].nunique())
        dict_output_data["mean"].append(input_data[feature].mean())
        dict_output_data["max"].append(input_data[feature].max())
        dict_output_data["min"].append(input_data[feature].min())
        dict_output_data["std"].append(input_data[feature].std())
        dict_output_data["perc25"].append(input_data[feature].quantile(.25))
        dict_output_data["perc50"].append(input_data[feature].quantile(.50))
        dict_output_data["perc75"].append(input_data[feature].quantile(.75))
    output_data = pd.DataFrame(dict_output_data)
    return output_data

In [7]:
eda_numerical(extract_csv_numerical)

variable  number_nan  number_distinct  \
0                            threads           0                1   
1   committed_instructions_per_cycle          13               10   
2         branch_prediction_accuracy          13                6   
3                       instructions          13               13   
4             accesses_mod_shared_mm           0               20   
5             accesses_mod_shared_l3           0               24   
6                 hits_mod_shared_l3           0               22   
7               misses_mod_shared_l3           0               23   
8                reads_mod_shared_l3           0               24   
9               writes_mod_shared_l3           0               24   
10                        hw_threads           0                1   
11                            cycles           0               23   
12                      dispatch_ipc           0               21   
13                         issue_ipc           0               20   
14                      commit_total           0               16   
15                        commit_ipc           0               21   
16                   commit_pred_acc           0               16   
17          issue_commit_totals_diff           0               24   
18        dispatch_issue_totals_diff           0               24   

            mean           max           min           std        perc25  \
0   8.000000e+00  8.000000e+00  8.000000e+00  0.000000e+00  8.000000e+00   
1   1.336156e+00  2.273000e+00  8.705000e-01  5.770632e-01  8.712000e-01   
2   9.219760e-01  9.693000e-01  8.384000e-01  5.854931e-02  8.385000e-01   
3   2.408596e+09  8.025928e+09  2.594862e+08  2.795062e+09  2.594868e+08   
4   7.804804e+05  4.490318e+06  8.891000e+03  1.419480e+06  1.009800e+04   
5   1.731199e+06  8.976851e+06  1.038300e+04  3.044462e+06  1.286800e+04   
6   5.207974e+04  4.813980e+05  1.450000e+03  1.228972e+05  2.723000e+03   
7   1.679119e+06  8.957287e+06  8.933000e+03  2.973641e+06  1.018200e+04   
8   6.246381e+05  4.171067e+06  3.314000e+03  1.280958e+06  7.795000e+03   
9   2.079221e+05  1.340272e+06  5.015000e+03  3.851416e+05  5.030500e+03   
10  1.600000e+01  1.600000e+01  1.600000e+01  0.000000e+00  1.600000e+01   
11  4.329924e+09  3.100945e+10  2.081956e+08  7.017706e+09  2.371362e+08   
12  2.358226e+00  5.716000e+00  4.550000e-01  1.493033e+00  1.099200e+00   
13  2.270603e+00  5.378000e+00  4.104000e-01  1.442046e+00  1.049775e+00   
14  4.641821e+09  1.937966e+10  4.458042e+08  4.974494e+09  4.458042e+08   
15  2.216621e+00  5.304000e+00  3.805000e-01  1.440547e+00  9.926250e-01   
16  9.231500e-01  9.693000e-01  8.378000e-01  5.039245e-02  9.188000e-01   
17  1.846842e+08  1.781152e+09  1.629116e+07  3.679298e+08  1.646418e+07   
18  3.091018e+08  3.058018e+09  1.288301e+07  5.918189e+08  1.632334e+07   

          perc50        perc75  
0   8.000000e+00  8.000000e+00  
1   9.922000e-01  2.028000e+00  
2   9.600000e-01  9.604000e-01  
3   2.596326e+08  5.034183e+09  
4   1.037200e+04  7.486330e+05  
5   1.291150e+04  1.839909e+06  
6   2.740000e+03  2.286875e+04  
7   1.045000e+04  1.772611e+06  
8   7.868500e+03  5.297285e+05  
9   7.098500e+03  2.942758e+05  
10  1.600000e+01  1.600000e+01  
11  1.525996e+09  4.938660e+09  
12  2.194500e+00  2.408500e+00  
13  2.172000e+00  2.367750e+00  
14  4.149421e+09  7.028781e+09  
15  2.139000e+00  2.336000e+00  
16  9.513500e-01  9.604000e-01  
17  6.916367e+07  1.128291e+08  
18  1.460997e+08  2.603590e+08

In [8]:
extract_csv_string = extract_csv.select_dtypes(exclude=[np.number])
extract_csv_string.head()

program_name width l1_cache l2_cache l3_cache
0     raytrace     4      64k       1m      16m
1     raytrace     4      32k       1m      16m
2     raytrace     4      32k       2m      32m
3     raytrace     4      64k       2m      32m
4    swaptions     4      64k       1m      32m

In [9]:
def eda_string(input_data):
    features = list(input_data)
    dict_output_data = {"variable":[],
                        "number_nan":[],
                        "number_distinct":[]
                       }
    for feature in features:
        dict_output_data["variable"].append(feature)
        dict_output_data["number_nan"].append(input_data[feature].isna().sum())
        dict_output_data["number_distinct"].append(input_data[feature].nunique())
    output_data = pd.DataFrame(dict_output_data)
    return output_data

In [10]:
eda_string(extract_csv_string)

variable  number_nan  number_distinct
0  program_name           0                5
1         width           0                2
2      l1_cache           0                2
3      l2_cache           0                2
4      l3_cache           0                2

# Missing at random?
We will compare the distributions of the extracts with and without missing value (rows).

In [11]:
miss_filter = eda_numerical(extract_csv_numerical)['number_nan'] > 0
print(eda_numerical(extract_csv_numerical)[miss_filter].variable)

1    committed_instructions_per_cycle
2          branch_prediction_accuracy
3                        instructions
Name: variable, dtype: object


In [12]:
vars_with_missing = list(eda_numerical(extract_csv_numerical)[miss_filter].variable)
for var in vars_with_missing:
    miss_column = extract_csv_numerical[var]
    only_na = extract_csv_numerical[miss_column.isna()]
    print(eda_numerical(only_na))

                            variable  number_nan  number_distinct  \
0                            threads           0                1   
1   committed_instructions_per_cycle          13                0   
2         branch_prediction_accuracy          13                0   
3                       instructions          13                0   
4             accesses_mod_shared_mm           0               12   
5             accesses_mod_shared_l3           0               12   
6                 hits_mod_shared_l3           0               12   
7               misses_mod_shared_l3           0               12   
8                reads_mod_shared_l3           0               12   
9               writes_mod_shared_l3           0               12   
10                        hw_threads           0                1   
11                            cycles           0               12   
12                      dispatch_ipc           0               12   
13                         issue_i

The fields with missing values seem to be missing at random, since other fields change dramatically after excluding non-missing values. Since they are missing at random, we could impute via mean or median by groups.

We consider the standard deviations of all three variables with missing variables to be high, so we will impute by medians (labeled 'perc50' above).

# New Dataset without missing values

In [13]:
#extract_csv
miss_filter = eda_numerical(extract_csv_numerical)['number_nan'] > 0
vars_with_missing = list(eda_numerical(extract_csv_numerical)[miss_filter].variable)
extract_csv[vars_with_missing].head()

committed_instructions_per_cycle  branch_prediction_accuracy  instructions
0                               NaN                         NaN           NaN
1                               NaN                         NaN           NaN
2                               NaN                         NaN           NaN
3                               NaN                         NaN           NaN
4                             2.268                      0.8384  5.034279e+09

In [14]:
# Creating filter of which to impute by median - Part 1
CIPC_filter = extract_csv.groupby('program_name')['committed_instructions_per_cycle'].\
apply(lambda x: x.notnull().sum()/len(x)*100).reset_index(name='percent')

BPA_filter = extract_csv.groupby('program_name')['branch_prediction_accuracy'].\
apply(lambda x: x.notnull().sum()/len(x)*100).reset_index(name='percent')

I_filter = extract_csv.groupby('program_name')['instructions'].\
apply(lambda x: x.notnull().sum()/len(x)*100).reset_index(name='percent')

print(CIPC_filter, BPA_filter, I_filter)

   program_name    percent
0  blackscholes  93.750000
1       canneal   0.000000
2  fluidanimate  66.666667
3      raytrace   0.000000
4     swaptions  88.888889    program_name    percent
0  blackscholes  93.750000
1       canneal   0.000000
2  fluidanimate  66.666667
3      raytrace   0.000000
4     swaptions  88.888889    program_name    percent
0  blackscholes  93.750000
1       canneal   0.000000
2  fluidanimate  66.666667
3      raytrace   0.000000
4     swaptions  88.888889


In [15]:
# Creating filter of which to impute by median - Part 2
# When the program is the below row, we will use the calculated value confirmed by Dr. Zahran, else we will 
# impute by group median.
CIPC_filter2 = CIPC_filter["program_name"][CIPC_filter['percent']==0].reset_index(name='program_name')
BPA_filter2 = BPA_filter["program_name"][BPA_filter['percent']==0].reset_index(name='program_name')
I_filter2 = I_filter["program_name"][I_filter['percent']==0].reset_index(name='program_name')
CIPC_filter3 = list(CIPC_filter2['program_name'])
BPA_filter3 = list(BPA_filter2['program_name'])
I_filter3 = list(I_filter2['program_name'])
print(CIPC_filter3, BPA_filter3, I_filter3)

['canneal', 'raytrace'] ['canneal', 'raytrace'] ['canneal', 'raytrace']


In [16]:
# Filling in committed_instructions_per_cycle
#in
extract_csv.loc[extract_csv['program_name'].isin(CIPC_filter3) & extract_csv['committed_instructions_per_cycle'].isna(), 'committed_instructions_per_cycle'] = (extract_csv['commit_total'] / extract_csv['cycles'])
# not in (Use ~)
#extract_csv.loc[~(extract_csv['program_name'].isin(CIPC_filter3)) & extract_csv['committed_instructions_per_cycle'].isna(), 'committed_instructions_per_cycle'] = (extract_csv['commit_total'] / extract_csv['cycles'])

In [17]:
extract_csv

program_name  threads width l1_cache l2_cache l3_cache  \
0       raytrace        8     4      64k       1m      16m   
1       raytrace        8     4      32k       1m      16m   
2       raytrace        8     4      32k       2m      32m   
3       raytrace        8     4      64k       2m      32m   
4      swaptions        8     4      64k       1m      32m   
5      swaptions        8     4      32k       2m      32m   
6      swaptions        8     4      64k       2m      32m   
7      swaptions        8     8      32k       2m      32m   
8      swaptions        8     4      32k       1m      32m   
9      swaptions        8     4      64k       1m      16m   
10     swaptions        8     4      32k       2m      16m   
11     swaptions        8     4      64k       2m      16m   
12     swaptions        8     4      32k       1m      16m   
13  blackscholes        8     4      32k       2m      16m   
14  blackscholes        8     8      32k       1m      16m   
15  blackscholes        8     4      64k       1m      16m   
16  blackscholes        8     8      64k       2m      16m   
17  blackscholes        8     4      32k       1m      16m   
18  blackscholes        8     8      32k       2m      16m   
19  blackscholes        8     4      64k       2m      16m   
20  blackscholes        8     8      64k       1m      16m   
21  blackscholes        8     4      32k       2m      32m   
22  blackscholes        8     8      32k       1m      32m   
23  blackscholes        8     4      64k       1m      32m   
24  blackscholes        8     8      64k       2m      32m   
25  blackscholes        8     4      32k       1m      32m   
26  blackscholes        8     8      32k       2m      32m   
27  blackscholes        8     4      64k       2m      32m   
28  blackscholes        8     8      64k       1m      32m   
29       canneal        8     4      64k       1m      16m   
30       canneal        8     4      32k       1m      16m   
31       canneal        8     4      64k       1m      32m   
32       canneal        8     4      32k       2m      32m   
33       canneal        8     4      64k       2m      32m   
34       canneal        8     4      32k       1m      32m   
35  fluidanimate        8     4      32k       1m      16m   
36  fluidanimate        8     4      64k       2m      32m   
37  fluidanimate        8     4      32k       2m      32m   

    committed_instructions_per_cycle  branch_prediction_accuracy  \
0                           0.697530                         NaN   
1                           0.675691                         NaN   
2                           0.624960                         NaN   
3                           0.643220                         NaN   
4                           2.268000                      0.8384   
5                           2.028000                      0.8384   
6                           2.273000                      0.8385   
7                                NaN                         NaN   
8                           2.028000                      0.8384   
9                           2.268000                      0.8384   
10                          2.028000                      0.8384   
11                          2.273000                      0.8385   
12                          2.028000                      0.8384   
13                          0.870500                      0.9600   
14                          0.991400                      0.9604   
15                          0.871200                      0.9601   
16                          0.992300                      0.9604   
17                          0.870500                      0.9600   
18                          0.991400                      0.9604   
19                          0.871200                      0.9600   
20                          0.992200                      0.9604   
21                          0.870500                      0.9600   
22                   

In [18]:
CIPC_filter4 = CIPC_filter["program_name"][CIPC_filter['percent']!=0].reset_index(name='program_name')
BPA_filter4 = BPA_filter["program_name"][BPA_filter['percent']!=0].reset_index(name='program_name')
I_filter4 = I_filter["program_name"][I_filter['percent']!=0].reset_index(name='program_name')
CIPC_filter5 = list(CIPC_filter4['program_name'])
BPA_filter5 = list(BPA_filter4['program_name'])
I_filter5 = list(I_filter4['program_name'])
print(CIPC_filter5, BPA_filter5, I_filter5)

['blackscholes', 'fluidanimate', 'swaptions'] ['blackscholes', 'fluidanimate', 'swaptions'] ['blackscholes', 'fluidanimate', 'swaptions']


In [19]:
median_df = extract_csv[extract_csv['program_name'].isin(CIPC_filter5)].groupby('program_name')['committed_instructions_per_cycle'].\
apply(lambda x: x.median()).reset_index(name='median')
print(median_df)

   program_name  median
0  blackscholes  0.9914
1  fluidanimate  1.0895
2     swaptions  2.1480


In [20]:
extract_csv.loc[extract_csv['program_name'].isin(['blackscholes']) & extract_csv['committed_instructions_per_cycle'].isna() , 'committed_instructions_per_cycle'] = median_df[median_df['program_name'] == 'blackscholes']['median'][0]
#extract_csv.loc[extract_csv['program_name'].isin(['fluidanimate']) & extract_csv['committed_instructions_per_cycle'].isna() , 'committed_instructions_per_cycle'] = median_df[median_df['program_name'] == 'fluidanimate']['median'][0]
#extract_csv.loc[extract_csv['program_name'].isin(['swaptions']) & extract_csv['committed_instructions_per_cycle'].isna() , 'committed_instructions_per_cycle'] = median_df[median_df['program_name'] == 'swaptions']['median'][0]

In [21]:
extract_csv.loc[extract_csv['program_name'].isin(['fluidanimate']) & extract_csv['committed_instructions_per_cycle'].isna() , 'committed_instructions_per_cycle'] = 1.0895

In [22]:
extract_csv.loc[extract_csv['program_name'].isin(['swaptions']) & extract_csv['committed_instructions_per_cycle'].isna() , 'committed_instructions_per_cycle'] = 2.1480

In [23]:
extract_csv

program_name  threads width l1_cache l2_cache l3_cache  \
0       raytrace        8     4      64k       1m      16m   
1       raytrace        8     4      32k       1m      16m   
2       raytrace        8     4      32k       2m      32m   
3       raytrace        8     4      64k       2m      32m   
4      swaptions        8     4      64k       1m      32m   
5      swaptions        8     4      32k       2m      32m   
6      swaptions        8     4      64k       2m      32m   
7      swaptions        8     8      32k       2m      32m   
8      swaptions        8     4      32k       1m      32m   
9      swaptions        8     4      64k       1m      16m   
10     swaptions        8     4      32k       2m      16m   
11     swaptions        8     4      64k       2m      16m   
12     swaptions        8     4      32k       1m      16m   
13  blackscholes        8     4      32k       2m      16m   
14  blackscholes        8     8      32k       1m      16m   
15  blackscholes        8     4      64k       1m      16m   
16  blackscholes        8     8      64k       2m      16m   
17  blackscholes        8     4      32k       1m      16m   
18  blackscholes        8     8      32k       2m      16m   
19  blackscholes        8     4      64k       2m      16m   
20  blackscholes        8     8      64k       1m      16m   
21  blackscholes        8     4      32k       2m      32m   
22  blackscholes        8     8      32k       1m      32m   
23  blackscholes        8     4      64k       1m      32m   
24  blackscholes        8     8      64k       2m      32m   
25  blackscholes        8     4      32k       1m      32m   
26  blackscholes        8     8      32k       2m      32m   
27  blackscholes        8     4      64k       2m      32m   
28  blackscholes        8     8      64k       1m      32m   
29       canneal        8     4      64k       1m      16m   
30       canneal        8     4      32k       1m      16m   
31       canneal        8     4      64k       1m      32m   
32       canneal        8     4      32k       2m      32m   
33       canneal        8     4      64k       2m      32m   
34       canneal        8     4      32k       1m      32m   
35  fluidanimate        8     4      32k       1m      16m   
36  fluidanimate        8     4      64k       2m      32m   
37  fluidanimate        8     4      32k       2m      32m   

    committed_instructions_per_cycle  branch_prediction_accuracy  \
0                           0.697530                         NaN   
1                           0.675691                         NaN   
2                           0.624960                         NaN   
3                           0.643220                         NaN   
4                           2.268000                      0.8384   
5                           2.028000                      0.8384   
6                           2.273000                      0.8385   
7                           2.148000                         NaN   
8                           2.028000                      0.8384   
9                           2.268000                      0.8384   
10                          2.028000                      0.8384   
11                          2.273000                      0.8385   
12                          2.028000                      0.8384   
13                          0.870500                      0.9600   
14                          0.991400                      0.9604   
15                          0.871200                      0.9601   
16                          0.992300                      0.9604   
17                          0.870500                      0.9600   
18                          0.991400                      0.9604   
19                          0.871200                      0.9600   
20                          0.992200                      0.9604   
21                          0.870500                      0.9600   
22                   

In [24]:
# branch_prediction_accuracy and commit_pred_acc are the same, so we will drop branch_prediction_accuracy
extract_csv[['branch_prediction_accuracy', 'commit_pred_acc']] 

branch_prediction_accuracy  commit_pred_acc
0                          NaN           0.9427
1                          NaN           0.9411
2                          NaN           0.9194
3                          NaN           0.9236
4                       0.8384           0.8384
5                       0.8384           0.8384
6                       0.8385           0.8385
7                          NaN           0.8378
8                       0.8384           0.8384
9                       0.8384           0.8384
10                      0.8384           0.8384
11                      0.8385           0.8385
12                      0.8384           0.8384
13                      0.9600           0.9600
14                      0.9604           0.9604
15                      0.9601           0.9601
16                      0.9604           0.9604
17                      0.9600           0.9600
18                      0.9604           0.9604
19                      0.9600           0.9600
20                      0.9604           0.9604
21                      0.9600           0.9600
22                      0.9604           0.9604
23                      0.9601           0.9601
24                      0.9604           0.9604
25                         NaN           0.9600
26                      0.9604           0.9604
27                      0.9600           0.9600
28                      0.9604           0.9604
29                         NaN           0.9225
30                         NaN           0.9188
31                         NaN           0.9408
32                         NaN           0.9190
33                         NaN           0.9190
34                         NaN           0.9188
35                         NaN           0.9668
36                      0.9693           0.9693
37                      0.9693           0.9693

In [25]:
extract_csv.drop(columns=['branch_prediction_accuracy'], inplace=True)
extract_csv

program_name  threads width l1_cache l2_cache l3_cache  \
0       raytrace        8     4      64k       1m      16m   
1       raytrace        8     4      32k       1m      16m   
2       raytrace        8     4      32k       2m      32m   
3       raytrace        8     4      64k       2m      32m   
4      swaptions        8     4      64k       1m      32m   
5      swaptions        8     4      32k       2m      32m   
6      swaptions        8     4      64k       2m      32m   
7      swaptions        8     8      32k       2m      32m   
8      swaptions        8     4      32k       1m      32m   
9      swaptions        8     4      64k       1m      16m   
10     swaptions        8     4      32k       2m      16m   
11     swaptions        8     4      64k       2m      16m   
12     swaptions        8     4      32k       1m      16m   
13  blackscholes        8     4      32k       2m      16m   
14  blackscholes        8     8      32k       1m      16m   
15  blackscholes        8     4      64k       1m      16m   
16  blackscholes        8     8      64k       2m      16m   
17  blackscholes        8     4      32k       1m      16m   
18  blackscholes        8     8      32k       2m      16m   
19  blackscholes        8     4      64k       2m      16m   
20  blackscholes        8     8      64k       1m      16m   
21  blackscholes        8     4      32k       2m      32m   
22  blackscholes        8     8      32k       1m      32m   
23  blackscholes        8     4      64k       1m      32m   
24  blackscholes        8     8      64k       2m      32m   
25  blackscholes        8     4      32k       1m      32m   
26  blackscholes        8     8      32k       2m      32m   
27  blackscholes        8     4      64k       2m      32m   
28  blackscholes        8     8      64k       1m      32m   
29       canneal        8     4      64k       1m      16m   
30       canneal        8     4      32k       1m      16m   
31       canneal        8     4      64k       1m      32m   
32       canneal        8     4      32k       2m      32m   
33       canneal        8     4      64k       2m      32m   
34       canneal        8     4      32k       1m      32m   
35  fluidanimate        8     4      32k       1m      16m   
36  fluidanimate        8     4      64k       2m      32m   
37  fluidanimate        8     4      32k       2m      32m   

    committed_instructions_per_cycle  instructions  accesses_mod_shared_mm  \
0                           0.697530           NaN                  153172   
1                           0.675691           NaN                  604276   
2                           0.624960           NaN                 2249433   
3                           0.643220           NaN                 1464840   
4                           2.268000  5.034279e+09                   10710   
5                           2.028000  5.034183e+09                   10583   
6                           2.273000  5.033521e+09                    9813   
7                           2.148000           NaN                    8891   
8                           2.028000  5.034183e+09                   10583   
9                           2.268000  5.034279e+09                   10710   
10                          2.028000  5.034183e+09                   10583   
11                          2.273000  5.033521e+09                    9813   
12                          2.028000  5.034183e+09                   10583   
13                          0.870500  2.594864e+08                   10097   
14                          0.991400  2.596287e+08                   10160   
15                          0.871200  2.594862e+08                   10097   
16                          0.992300  2.596349e+08                   10161   
17                          0.870500  2.594862e+08                   10098   
18                          0.991400  2.596287e+08                   10160   
19                       

In [26]:
# Filling in instructions
#in
extract_csv.loc[extract_csv['program_name'].isin(I_filter3) & extract_csv['instructions'].isna(), 'instructions'] = extract_csv['commit_total'] 
# not in (Use ~)
#extract_csv.loc[~(extract_csv['program_name'].isin(CIPC_filter3)) & extract_csv['committed_instructions_per_cycle'].isna(), 'committed_instructions_per_cycle'] = (extract_csv['commit_total'] / extract_csv['cycles'])

In [27]:
extract_csv

program_name  threads width l1_cache l2_cache l3_cache  \
0       raytrace        8     4      64k       1m      16m   
1       raytrace        8     4      32k       1m      16m   
2       raytrace        8     4      32k       2m      32m   
3       raytrace        8     4      64k       2m      32m   
4      swaptions        8     4      64k       1m      32m   
5      swaptions        8     4      32k       2m      32m   
6      swaptions        8     4      64k       2m      32m   
7      swaptions        8     8      32k       2m      32m   
8      swaptions        8     4      32k       1m      32m   
9      swaptions        8     4      64k       1m      16m   
10     swaptions        8     4      32k       2m      16m   
11     swaptions        8     4      64k       2m      16m   
12     swaptions        8     4      32k       1m      16m   
13  blackscholes        8     4      32k       2m      16m   
14  blackscholes        8     8      32k       1m      16m   
15  blackscholes        8     4      64k       1m      16m   
16  blackscholes        8     8      64k       2m      16m   
17  blackscholes        8     4      32k       1m      16m   
18  blackscholes        8     8      32k       2m      16m   
19  blackscholes        8     4      64k       2m      16m   
20  blackscholes        8     8      64k       1m      16m   
21  blackscholes        8     4      32k       2m      32m   
22  blackscholes        8     8      32k       1m      32m   
23  blackscholes        8     4      64k       1m      32m   
24  blackscholes        8     8      64k       2m      32m   
25  blackscholes        8     4      32k       1m      32m   
26  blackscholes        8     8      32k       2m      32m   
27  blackscholes        8     4      64k       2m      32m   
28  blackscholes        8     8      64k       1m      32m   
29       canneal        8     4      64k       1m      16m   
30       canneal        8     4      32k       1m      16m   
31       canneal        8     4      64k       1m      32m   
32       canneal        8     4      32k       2m      32m   
33       canneal        8     4      64k       2m      32m   
34       canneal        8     4      32k       1m      32m   
35  fluidanimate        8     4      32k       1m      16m   
36  fluidanimate        8     4      64k       2m      32m   
37  fluidanimate        8     4      32k       2m      32m   

    committed_instructions_per_cycle  instructions  accesses_mod_shared_mm  \
0                           0.697530  3.601321e+09                  153172   
1                           0.675691  9.334926e+09                  604276   
2                           0.624960  1.937966e+10                 2249433   
3                           0.643220  1.549406e+10                 1464840   
4                           2.268000  5.034279e+09                   10710   
5                           2.028000  5.034183e+09                   10583   
6                           2.273000  5.033521e+09                    9813   
7                           2.148000           NaN                    8891   
8                           2.028000  5.034183e+09                   10583   
9                           2.268000  5.034279e+09                   10710   
10                          2.028000  5.034183e+09                   10583   
11                          2.273000  5.033521e+09                    9813   
12                          2.028000  5.034183e+09                   10583   
13                          0.870500  2.594864e+08                   10097   
14                          0.991400  2.596287e+08                   10160   
15                          0.871200  2.594862e+08                   10097   
16                          0.992300  2.596349e+08                   10161   
17                          0.870500  2.594862e+08                   10098   
18                          0.991400  2.596287e+08                   10160   
19                       

In [28]:
median_df = extract_csv[extract_csv['program_name'].isin(I_filter5)].groupby('program_name')['instructions'].\
apply(lambda x: x.median()).reset_index(name='median')
print(median_df)

   program_name        median
0  blackscholes  2.596287e+08
1  fluidanimate  8.024558e+09
2     swaptions  5.034183e+09


In [29]:
extract_csv.loc[extract_csv['program_name'].isin(['blackscholes']) & extract_csv['instructions'].isna() , 'instructions'] = median_df[median_df['program_name'] == 'blackscholes']['median'][0]

In [30]:
extract_csv.loc[extract_csv['program_name'].isin(['fluidanimate']) & extract_csv['instructions'].isna() , 'instructions'] = 8.024558e+09

In [31]:
extract_csv.loc[extract_csv['program_name'].isin(['swaptions']) & extract_csv['instructions'].isna() , 'instructions'] = 5.034183e+09

In [32]:
extract_csv.drop(columns=['commit_total'], inplace=True)
extract_csv

program_name  threads width l1_cache l2_cache l3_cache  \
0       raytrace        8     4      64k       1m      16m   
1       raytrace        8     4      32k       1m      16m   
2       raytrace        8     4      32k       2m      32m   
3       raytrace        8     4      64k       2m      32m   
4      swaptions        8     4      64k       1m      32m   
5      swaptions        8     4      32k       2m      32m   
6      swaptions        8     4      64k       2m      32m   
7      swaptions        8     8      32k       2m      32m   
8      swaptions        8     4      32k       1m      32m   
9      swaptions        8     4      64k       1m      16m   
10     swaptions        8     4      32k       2m      16m   
11     swaptions        8     4      64k       2m      16m   
12     swaptions        8     4      32k       1m      16m   
13  blackscholes        8     4      32k       2m      16m   
14  blackscholes        8     8      32k       1m      16m   
15  blackscholes        8     4      64k       1m      16m   
16  blackscholes        8     8      64k       2m      16m   
17  blackscholes        8     4      32k       1m      16m   
18  blackscholes        8     8      32k       2m      16m   
19  blackscholes        8     4      64k       2m      16m   
20  blackscholes        8     8      64k       1m      16m   
21  blackscholes        8     4      32k       2m      32m   
22  blackscholes        8     8      32k       1m      32m   
23  blackscholes        8     4      64k       1m      32m   
24  blackscholes        8     8      64k       2m      32m   
25  blackscholes        8     4      32k       1m      32m   
26  blackscholes        8     8      32k       2m      32m   
27  blackscholes        8     4      64k       2m      32m   
28  blackscholes        8     8      64k       1m      32m   
29       canneal        8     4      64k       1m      16m   
30       canneal        8     4      32k       1m      16m   
31       canneal        8     4      64k       1m      32m   
32       canneal        8     4      32k       2m      32m   
33       canneal        8     4      64k       2m      32m   
34       canneal        8     4      32k       1m      32m   
35  fluidanimate        8     4      32k       1m      16m   
36  fluidanimate        8     4      64k       2m      32m   
37  fluidanimate        8     4      32k       2m      32m   

    committed_instructions_per_cycle  instructions  accesses_mod_shared_mm  \
0                           0.697530  3.601321e+09                  153172   
1                           0.675691  9.334926e+09                  604276   
2                           0.624960  1.937966e+10                 2249433   
3                           0.643220  1.549406e+10                 1464840   
4                           2.268000  5.034279e+09                   10710   
5                           2.028000  5.034183e+09                   10583   
6                           2.273000  5.033521e+09                    9813   
7                           2.148000  5.034183e+09                    8891   
8                           2.028000  5.034183e+09                   10583   
9                           2.268000  5.034279e+09                   10710   
10                          2.028000  5.034183e+09                   10583   
11                          2.273000  5.033521e+09                    9813   
12                          2.028000  5.034183e+09                   10583   
13                          0.870500  2.594864e+08                   10097   
14                          0.991400  2.596287e+08                   10160   
15                          0.871200  2.594862e+08                   10097   
16                          0.992300  2.596349e+08                   10161   
17                          0.870500  2.594862e+08                   10098   
18                          0.991400  2.596287e+08                   10160   
19                       

In [33]:
extract_csv

program_name  threads width l1_cache l2_cache l3_cache  \
0       raytrace        8     4      64k       1m      16m   
1       raytrace        8     4      32k       1m      16m   
2       raytrace        8     4      32k       2m      32m   
3       raytrace        8     4      64k       2m      32m   
4      swaptions        8     4      64k       1m      32m   
5      swaptions        8     4      32k       2m      32m   
6      swaptions        8     4      64k       2m      32m   
7      swaptions        8     8      32k       2m      32m   
8      swaptions        8     4      32k       1m      32m   
9      swaptions        8     4      64k       1m      16m   
10     swaptions        8     4      32k       2m      16m   
11     swaptions        8     4      64k       2m      16m   
12     swaptions        8     4      32k       1m      16m   
13  blackscholes        8     4      32k       2m      16m   
14  blackscholes        8     8      32k       1m      16m   
15  blackscholes        8     4      64k       1m      16m   
16  blackscholes        8     8      64k       2m      16m   
17  blackscholes        8     4      32k       1m      16m   
18  blackscholes        8     8      32k       2m      16m   
19  blackscholes        8     4      64k       2m      16m   
20  blackscholes        8     8      64k       1m      16m   
21  blackscholes        8     4      32k       2m      32m   
22  blackscholes        8     8      32k       1m      32m   
23  blackscholes        8     4      64k       1m      32m   
24  blackscholes        8     8      64k       2m      32m   
25  blackscholes        8     4      32k       1m      32m   
26  blackscholes        8     8      32k       2m      32m   
27  blackscholes        8     4      64k       2m      32m   
28  blackscholes        8     8      64k       1m      32m   
29       canneal        8     4      64k       1m      16m   
30       canneal        8     4      32k       1m      16m   
31       canneal        8     4      64k       1m      32m   
32       canneal        8     4      32k       2m      32m   
33       canneal        8     4      64k       2m      32m   
34       canneal        8     4      32k       1m      32m   
35  fluidanimate        8     4      32k       1m      16m   
36  fluidanimate        8     4      64k       2m      32m   
37  fluidanimate        8     4      32k       2m      32m   

    committed_instructions_per_cycle  instructions  accesses_mod_shared_mm  \
0                           0.697530  3.601321e+09                  153172   
1                           0.675691  9.334926e+09                  604276   
2                           0.624960  1.937966e+10                 2249433   
3                           0.643220  1.549406e+10                 1464840   
4                           2.268000  5.034279e+09                   10710   
5                           2.028000  5.034183e+09                   10583   
6                           2.273000  5.033521e+09                    9813   
7                           2.148000  5.034183e+09                    8891   
8                           2.028000  5.034183e+09                   10583   
9                           2.268000  5.034279e+09                   10710   
10                          2.028000  5.034183e+09                   10583   
11                          2.273000  5.033521e+09                    9813   
12                          2.028000  5.034183e+09                   10583   
13                          0.870500  2.594864e+08                   10097   
14                          0.991400  2.596287e+08                   10160   
15                          0.871200  2.594862e+08                   10097   
16                          0.992300  2.596349e+08                   10161   
17                          0.870500  2.594862e+08                   10098   
18                          0.991400  2.596287e+08                   10160   
19                       

# Preparation Section for Models

In [34]:
#Scale the features only, not the dependent variable
from sklearn import preprocessing
extract_csv_numerical2 = extract_csv.select_dtypes(include=[np.number])
input_cols = [col for col in extract_csv_numerical2.columns if col not in ['cycles']]
extract_csv_features_only = extract_csv_numerical2[input_cols]
data_scaled = preprocessing.scale(extract_csv_features_only)
data_scaled_df = pd.DataFrame(data_scaled, columns = input_cols)
data_scaled_df.head()

/home/anthony/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/_data.py:173: UserWarning: Numerical issues were encountered when centering the data and might not be solved. Dataset may contain too large values. You may need to prescale your features.
  warnings.warn("Numerical issues were encountered "


threads  committed_instructions_per_cycle  instructions  \
0      0.0                         -0.706834     -0.039454   
1      0.0                         -0.742798      1.301903   
2      0.0                         -0.826343      3.651833   
3      0.0                         -0.796271      2.742811   
4      0.0                          1.879429      0.295782   

   accesses_mod_shared_mm  accesses_mod_shared_l3  hits_mod_shared_l3  \
0               -0.447860               -0.456373           -0.362257   
1               -0.125799               -0.086542           -0.182080   
2                1.048744                1.184159           -0.210529   
3                0.488591                0.555324           -0.239531   
4               -0.549570               -0.572090           -0.415527   

   misses_mod_shared_l3  reads_mod_shared_l3  writes_mod_shared_l3  \
0             -0.452270            -0.438479             -0.307876   
1             -0.081078            -0.264835              0.359078   
2              1.221062             0.246103              2.979554   
3              0.578450            -0.011838              1.763695   
4             -0.568542            -0.489985             -0.528429   

   hw_threads  dispatch_ipc  issue_ipc  commit_ipc  commit_pred_acc  \
0         0.0     -1.058625  -1.068139   -1.068700         0.393163   
1         0.0     -1.071793  -1.084232   -1.084036         0.360986   
2         0.0     -1.070571  -1.116138   -1.119704        -0.075415   
3         0.0     -1.064734  -1.103769   -1.106900         0.009050   
4         0.0      1.668937   1.669353    1.677408        -1.704375   

   issue_commit_totals_diff  dispatch_issue_totals_diff  
0                  0.247103                   -0.105791  
1                  1.474237                    0.686997  
2                  4.397301                    4.707210  
3                  3.260521                    3.163643  
4                 -0.318184                   -0.083424

In [35]:
extract_csv.update(data_scaled_df)
extract_csv.head(100)

program_name  threads width l1_cache l2_cache l3_cache  \
0       raytrace      0.0     4      64k       1m      16m   
1       raytrace      0.0     4      32k       1m      16m   
2       raytrace      0.0     4      32k       2m      32m   
3       raytrace      0.0     4      64k       2m      32m   
4      swaptions      0.0     4      64k       1m      32m   
5      swaptions      0.0     4      32k       2m      32m   
6      swaptions      0.0     4      64k       2m      32m   
7      swaptions      0.0     8      32k       2m      32m   
8      swaptions      0.0     4      32k       1m      32m   
9      swaptions      0.0     4      64k       1m      16m   
10     swaptions      0.0     4      32k       2m      16m   
11     swaptions      0.0     4      64k       2m      16m   
12     swaptions      0.0     4      32k       1m      16m   
13  blackscholes      0.0     4      32k       2m      16m   
14  blackscholes      0.0     8      32k       1m      16m   
15  blackscholes      0.0     4      64k       1m      16m   
16  blackscholes      0.0     8      64k       2m      16m   
17  blackscholes      0.0     4      32k       1m      16m   
18  blackscholes      0.0     8      32k       2m      16m   
19  blackscholes      0.0     4      64k       2m      16m   
20  blackscholes      0.0     8      64k       1m      16m   
21  blackscholes      0.0     4      32k       2m      32m   
22  blackscholes      0.0     8      32k       1m      32m   
23  blackscholes      0.0     4      64k       1m      32m   
24  blackscholes      0.0     8      64k       2m      32m   
25  blackscholes      0.0     4      32k       1m      32m   
26  blackscholes      0.0     8      32k       2m      32m   
27  blackscholes      0.0     4      64k       2m      32m   
28  blackscholes      0.0     8      64k       1m      32m   
29       canneal      0.0     4      64k       1m      16m   
30       canneal      0.0     4      32k       1m      16m   
31       canneal      0.0     4      64k       1m      32m   
32       canneal      0.0     4      32k       2m      32m   
33       canneal      0.0     4      64k       2m      32m   
34       canneal      0.0     4      32k       1m      32m   
35  fluidanimate      0.0     4      32k       1m      16m   
36  fluidanimate      0.0     4      64k       2m      32m   
37  fluidanimate      0.0     4      32k       2m      32m   

    committed_instructions_per_cycle  instructions  accesses_mod_shared_mm  \
0                          -0.706834     -0.039454               -0.447860   
1                          -0.742798      1.301903               -0.125799   
2                          -0.826343      3.651833                1.048744   
3                          -0.796271      2.742811                0.488591   
4                           1.879429      0.295782               -0.549570   
5                           1.484195      0.295759               -0.549660   
6                           1.887663      0.295605               -0.550210   
7                           1.681812      0.295759               -0.550868   
8                           1.484195      0.295759               -0.549660   
9                           1.879429      0.295782               -0.549570   
10                          1.484195      0.295759               -0.549660   
11                          1.887663      0.295605               -0.550210   
12                          1.484195      0.295759               -0.549660   
13                         -0.421985     -0.821264               -0.550007   
14                         -0.222886     -0.821231               -0.549962   
15                         -0.420832     -0.821264               -0.550007   
16                         -0.221404     -0.821229               -0.549962   
17                         -0.421985     -0.821264               -0.550007   
18                         -0.222886     -0.821231               -0.549962   
19                       

In [36]:
extract_csv.count()

program_name                        38
threads                             38
width                               38
l1_cache                            38
l2_cache                            38
l3_cache                            38
committed_instructions_per_cycle    38
instructions                        38
accesses_mod_shared_mm              38
accesses_mod_shared_l3              38
hits_mod_shared_l3                  38
misses_mod_shared_l3                38
reads_mod_shared_l3                 38
writes_mod_shared_l3                38
hw_threads                          38
cycles                              38
dispatch_ipc                        38
issue_ipc                           38
commit_ipc                          38
commit_pred_acc                     38
issue_commit_totals_diff            38
dispatch_issue_totals_diff          38
dtype: int64

# One-Hot Encoding Categorical Variables

In [37]:
from numpy import array
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
#left-to-right column order alphabetical

In [38]:
# program_name

values = array(extract_csv['program_name'])
print(values)

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

alphabetized_values = list(extract_csv['program_name'].unique())
alphabetized_values.sort()
print(alphabetized_values)

df_program_name = pd.DataFrame(onehot_encoded, columns = alphabetized_values)
df_program_name.head(100)

extract_csv.drop(columns=['program_name'], inplace=True)

idx = 0
for header in alphabetized_values:
    extract_csv.insert(loc=idx, column=header, value=df_program_name[header])
    idx += 1
    
extract_csv.head(100)

['raytrace' 'raytrace' 'raytrace' 'raytrace' 'swaptions' 'swaptions'
 'swaptions' 'swaptions' 'swaptions' 'swaptions' 'swaptions' 'swaptions'
 'swaptions' 'blackscholes' 'blackscholes' 'blackscholes' 'blackscholes'
 'blackscholes' 'blackscholes' 'blackscholes' 'blackscholes'
 'blackscholes' 'blackscholes' 'blackscholes' 'blackscholes'
 'blackscholes' 'blackscholes' 'blackscholes' 'blackscholes' 'canneal'
 'canneal' 'canneal' 'canneal' 'canneal' 'canneal' 'fluidanimate'
 'fluidanimate' 'fluidanimate']
[3 3 3 3 4 4 4 4 4 4 4 4 4 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 2 2
 2]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 

blackscholes  canneal  fluidanimate  raytrace  swaptions  threads width  \
0            0.0      0.0           0.0       1.0        0.0      0.0     4   
1            0.0      0.0           0.0       1.0        0.0      0.0     4   
2            0.0      0.0           0.0       1.0        0.0      0.0     4   
3            0.0      0.0           0.0       1.0        0.0      0.0     4   
4            0.0      0.0           0.0       0.0        1.0      0.0     4   
5            0.0      0.0           0.0       0.0        1.0      0.0     4   
6            0.0      0.0           0.0       0.0        1.0      0.0     4   
7            0.0      0.0           0.0       0.0        1.0      0.0     8   
8            0.0      0.0           0.0       0.0        1.0      0.0     4   
9            0.0      0.0           0.0       0.0        1.0      0.0     4   
10           0.0      0.0           0.0       0.0        1.0      0.0     4   
11           0.0      0.0           0.0       0.0        1.0      0.0     4   
12           0.0      0.0           0.0       0.0        1.0      0.0     4   
13           1.0      0.0           0.0       0.0        0.0      0.0     4   
14           1.0      0.0           0.0       0.0        0.0      0.0     8   
15           1.0      0.0           0.0       0.0        0.0      0.0     4   
16           1.0      0.0           0.0       0.0        0.0      0.0     8   
17           1.0      0.0           0.0       0.0        0.0      0.0     4   
18           1.0      0.0           0.0       0.0        0.0      0.0     8   
19           1.0      0.0           0.0       0.0        0.0      0.0     4   
20           1.0      0.0           0.0       0.0        0.0      0.0     8   
21           1.0      0.0           0.0       0.0        0.0      0.0     4   
22           1.0      0.0           0.0       0.0        0.0      0.0     8   
23           1.0      0.0           0.0       0.0        0.0      0.0     4   
24           1.0      0.0           0.0       0.0        0.0      0.0     8   
25           1.0      0.0           0.0       0.0        0.0      0.0     4   
26           1.0      0.0           0.0       0.0        0.0      0.0     8   
27           1.0      0.0           0.0       0.0        0.0      0.0     4   
28           1.0      0.0           0.0       0.0        0.0      0.0     8   
29           0.0      1.0           0.0       0.0        0.0      0.0     4   
30           0.0      1.0           0.0       0.0        0.0      0.0     4   
31           0.0      1.0           0.0       0.0        0.0      0.0     4   
32           0.0      1.0           0.0       0.0        0.0      0.0     4   
33           0.0      1.0           0.0       0.0        0.0      0.0     4   
34           0.0      1.0           0.0       0.0        0.0      0.0     4   
35           0.0      0.0           1.0       0.0        0.0      0.0     4   
36           0.0      0.0           1.0       0.0        0.0      0.0     4   
37           0.0      0.0           1.0       0.0        0.0      0.0     4   

   l1_cache l2_cache l3_cache  ...  reads_mod_shared_l3  writes_mod_shared_l3  \
0       64k       1m      16m  ...            -0.438479             -0.307876   
1       32k       1m      16m  ...            -0.264835              0.359078   
2       32k       2m      32m  ...             0.246103              2.979554   
3       64k       2m      32m  ...            -0.011838              1.763695   
4       64k       1m      32m  ...            -0.489985             -0.528429   
5       32k       2m      32m  ...            -0.490114             -0.528426   
6       64k       2m      32m  ...            -0.490754             -0.528423   
7       32k       2m      32m  ...            -0.491557             -0.528615   
8       32k       1m      32m  ...            -0.490114             -0.528426   
9       64k       1m      16m  ...            -0.489985             -0.528429   
10      32k       2m      16m  

In [39]:
# l1_cache

values = array(extract_csv['l1_cache'])
print(values)

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

alphabetized_values = list(extract_csv['l1_cache'].unique())
alphabetized_values.sort()
print(alphabetized_values)

df_program_name = pd.DataFrame(onehot_encoded, columns = alphabetized_values)
df_program_name.head(100)

extract_csv.drop(columns=['l1_cache'], inplace=True)

idx = 0
for header in alphabetized_values:
    extract_csv.insert(loc=idx, column=header, value=df_program_name[header])
    idx += 1
    
extract_csv.head(100)

['64k' '32k' '32k' '64k' '64k' '32k' '64k' '32k' '32k' '64k' '32k' '64k'
 '32k' '32k' '32k' '64k' '64k' '32k' '32k' '64k' '64k' '32k' '32k' '64k'
 '64k' '32k' '32k' '64k' '64k' '64k' '32k' '64k' '32k' '64k' '32k' '32k'
 '64k' '32k']
[1 0 0 1 1 0 1 0 0 1 0 1 0 0 0 1 1 0 0 1 1 0 0 1 1 0 0 1 1 1 0 1 0 1 0 0 1
 0]
[[0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]]
['32k', '64k']


32k  64k  blackscholes  canneal  fluidanimate  raytrace  swaptions  \
0   0.0  1.0           0.0      0.0           0.0       1.0        0.0   
1   1.0  0.0           0.0      0.0           0.0       1.0        0.0   
2   1.0  0.0           0.0      0.0           0.0       1.0        0.0   
3   0.0  1.0           0.0      0.0           0.0       1.0        0.0   
4   0.0  1.0           0.0      0.0           0.0       0.0        1.0   
5   1.0  0.0           0.0      0.0           0.0       0.0        1.0   
6   0.0  1.0           0.0      0.0           0.0       0.0        1.0   
7   1.0  0.0           0.0      0.0           0.0       0.0        1.0   
8   1.0  0.0           0.0      0.0           0.0       0.0        1.0   
9   0.0  1.0           0.0      0.0           0.0       0.0        1.0   
10  1.0  0.0           0.0      0.0           0.0       0.0        1.0   
11  0.0  1.0           0.0      0.0           0.0       0.0        1.0   
12  1.0  0.0           0.0      0.0           0.0       0.0        1.0   
13  1.0  0.0           1.0      0.0           0.0       0.0        0.0   
14  1.0  0.0           1.0      0.0           0.0       0.0        0.0   
15  0.0  1.0           1.0      0.0           0.0       0.0        0.0   
16  0.0  1.0           1.0      0.0           0.0       0.0        0.0   
17  1.0  0.0           1.0      0.0           0.0       0.0        0.0   
18  1.0  0.0           1.0      0.0           0.0       0.0        0.0   
19  0.0  1.0           1.0      0.0           0.0       0.0        0.0   
20  0.0  1.0           1.0      0.0           0.0       0.0        0.0   
21  1.0  0.0           1.0      0.0           0.0       0.0        0.0   
22  1.0  0.0           1.0      0.0           0.0       0.0        0.0   
23  0.0  1.0           1.0      0.0           0.0       0.0        0.0   
24  0.0  1.0           1.0      0.0           0.0       0.0        0.0   
25  1.0  0.0           1.0      0.0           0.0       0.0        0.0   
26  1.0  0.0           1.0      0.0           0.0       0.0        0.0   
27  0.0  1.0           1.0      0.0           0.0       0.0        0.0   
28  0.0  1.0           1.0      0.0           0.0       0.0        0.0   
29  0.0  1.0           0.0      1.0           0.0       0.0        0.0   
30  1.0  0.0           0.0      1.0           0.0       0.0        0.0   
31  0.0  1.0           0.0      1.0           0.0       0.0        0.0   
32  1.0  0.0           0.0      1.0           0.0       0.0        0.0   
33  0.0  1.0           0.0      1.0           0.0       0.0        0.0   
34  1.0  0.0           0.0      1.0           0.0       0.0        0.0   
35  1.0  0.0           0.0      0.0           1.0       0.0        0.0   
36  0.0  1.0           0.0      0.0           1.0       0.0        0.0   
37  1.0  0.0           0.0      0.0           1.0       0.0        0.0   

    threads width l2_cache  ... reads_mod_shared_l3  writes_mod_shared_l3  \
0       0.0     4       1m  ...           -0.438479             -0.307876   
1       0.0     4       1m  ...           -0.264835              0.359078   
2       0.0     4       2m  ...            0.246103              2.979554   
3       0.0     4       2m  ...           -0.011838              1.763695   
4       0.0     4       1m  ...           -0.489985             -0.528429   
5       0.0     4       2m  ...           -0.490114             -0.528426   
6       0.0     4       2m  ...           -0.490754             -0.528423   
7       0.0     8       2m  ...           -0.491557             -0.528615   
8       0.0     4       1m  ...           -0.490114             -0.528426   
9       0.0     4       1m  ...           -0.489985             -0.528429   
10      0.0     4       2m  ...           -0.490114             -0.528426   
11      0.0     4       2m  ...           -0.490754             -0.528423   
12      0.0     4       1m  ...           -0.490114             -0.528426   
13      0.0     4       2m  ...        

In [40]:
# l2_cache

values = array(extract_csv['l2_cache'])
print(values)

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

alphabetized_values = list(extract_csv['l2_cache'].unique())
alphabetized_values.sort()
print(alphabetized_values)

df_program_name = pd.DataFrame(onehot_encoded, columns = alphabetized_values)
df_program_name.head(100)

extract_csv.drop(columns=['l2_cache'], inplace=True)

idx = 0
for header in alphabetized_values:
    extract_csv.insert(loc=idx, column=header, value=df_program_name[header])
    idx += 1
    
extract_csv.head(100)

['1m' '1m' '2m' '2m' '1m' '2m' '2m' '2m' '1m' '1m' '2m' '2m' '1m' '2m'
 '1m' '1m' '2m' '1m' '2m' '2m' '1m' '2m' '1m' '1m' '2m' '1m' '2m' '2m'
 '1m' '1m' '1m' '1m' '2m' '2m' '1m' '1m' '2m' '2m']
[0 0 1 1 0 1 1 1 0 0 1 1 0 1 0 0 1 0 1 1 0 1 0 0 1 0 1 1 0 0 0 0 1 1 0 0 1
 1]
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]
['1m', '2m']


1m   2m  32k  64k  blackscholes  canneal  fluidanimate  raytrace  \
0   1.0  0.0  0.0  1.0           0.0      0.0           0.0       1.0   
1   1.0  0.0  1.0  0.0           0.0      0.0           0.0       1.0   
2   0.0  1.0  1.0  0.0           0.0      0.0           0.0       1.0   
3   0.0  1.0  0.0  1.0           0.0      0.0           0.0       1.0   
4   1.0  0.0  0.0  1.0           0.0      0.0           0.0       0.0   
5   0.0  1.0  1.0  0.0           0.0      0.0           0.0       0.0   
6   0.0  1.0  0.0  1.0           0.0      0.0           0.0       0.0   
7   0.0  1.0  1.0  0.0           0.0      0.0           0.0       0.0   
8   1.0  0.0  1.0  0.0           0.0      0.0           0.0       0.0   
9   1.0  0.0  0.0  1.0           0.0      0.0           0.0       0.0   
10  0.0  1.0  1.0  0.0           0.0      0.0           0.0       0.0   
11  0.0  1.0  0.0  1.0           0.0      0.0           0.0       0.0   
12  1.0  0.0  1.0  0.0           0.0      0.0           0.0       0.0   
13  0.0  1.0  1.0  0.0           1.0      0.0           0.0       0.0   
14  1.0  0.0  1.0  0.0           1.0      0.0           0.0       0.0   
15  1.0  0.0  0.0  1.0           1.0      0.0           0.0       0.0   
16  0.0  1.0  0.0  1.0           1.0      0.0           0.0       0.0   
17  1.0  0.0  1.0  0.0           1.0      0.0           0.0       0.0   
18  0.0  1.0  1.0  0.0           1.0      0.0           0.0       0.0   
19  0.0  1.0  0.0  1.0           1.0      0.0           0.0       0.0   
20  1.0  0.0  0.0  1.0           1.0      0.0           0.0       0.0   
21  0.0  1.0  1.0  0.0           1.0      0.0           0.0       0.0   
22  1.0  0.0  1.0  0.0           1.0      0.0           0.0       0.0   
23  1.0  0.0  0.0  1.0           1.0      0.0           0.0       0.0   
24  0.0  1.0  0.0  1.0           1.0      0.0           0.0       0.0   
25  1.0  0.0  1.0  0.0           1.0      0.0           0.0       0.0   
26  0.0  1.0  1.0  0.0           1.0      0.0           0.0       0.0   
27  0.0  1.0  0.0  1.0           1.0      0.0           0.0       0.0   
28  1.0  0.0  0.0  1.0           1.0      0.0           0.0       0.0   
29  1.0  0.0  0.0  1.0           0.0      1.0           0.0       0.0   
30  1.0  0.0  1.0  0.0           0.0      1.0           0.0       0.0   
31  1.0  0.0  0.0  1.0           0.0      1.0           0.0       0.0   
32  0.0  1.0  1.0  0.0           0.0      1.0           0.0       0.0   
33  0.0  1.0  0.0  1.0           0.0      1.0           0.0       0.0   
34  1.0  0.0  1.0  0.0           0.0      1.0           0.0       0.0   
35  1.0  0.0  1.0  0.0           0.0      0.0           1.0       0.0   
36  0.0  1.0  0.0  1.0           0.0      0.0           1.0       0.0   
37  0.0  1.0  1.0  0.0           0.0      0.0           1.0       0.0   

    swaptions  threads  ... reads_mod_shared_l3 writes_mod_shared_l3  \
0         0.0      0.0  ...           -0.438479            -0.307876   
1         0.0      0.0  ...           -0.264835             0.359078   
2         0.0      0.0  ...            0.246103             2.979554   
3         0.0      0.0  ...           -0.011838             1.763695   
4         1.0      0.0  ...           -0.489985            -0.528429   
5         1.0      0.0  ...           -0.490114            -0.528426   
6         1.0      0.0  ...           -0.490754            -0.528423   
7         1.0      0.0  ...           -0.491557            -0.528615   
8         1.0      0.0  ...           -0.490114            -0.528426   
9         1.0      0.0  ...           -0.489985            -0.528429   
10        1.0      0.0  ...           -0.490114            -0.528426   
11        1.0      0.0  ...           -0.490754            -0.528423   
12        1.0      0.0  ...           -0.490114            -0.528426   
13        0.0      0.0  ...           -0.488012            -0.533870   
14        0.0      0.0  ...           -0.487954            -0.533907   
15   

In [41]:
# l3_cache

values = array(extract_csv['l3_cache'])
print(values)

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

alphabetized_values = list(extract_csv['l3_cache'].unique())
alphabetized_values.sort()
print(alphabetized_values)

df_program_name = pd.DataFrame(onehot_encoded, columns = alphabetized_values)
df_program_name.head(100)

extract_csv.drop(columns=['l3_cache'], inplace=True)

idx = 0
for header in alphabetized_values:
    extract_csv.insert(loc=idx, column=header, value=df_program_name[header])
    idx += 1
    
extract_csv.head(100)

['16m' '16m' '32m' '32m' '32m' '32m' '32m' '32m' '32m' '16m' '16m' '16m'
 '16m' '16m' '16m' '16m' '16m' '16m' '16m' '16m' '16m' '32m' '32m' '32m'
 '32m' '32m' '32m' '32m' '32m' '16m' '16m' '32m' '32m' '32m' '32m' '16m'
 '32m' '32m']
[0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 0 0 1 1 1 1 0 1
 1]
[[1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [0. 1.]]
['16m', '32m']


16m  32m   1m   2m  32k  64k  blackscholes  canneal  fluidanimate  \
0   1.0  0.0  1.0  0.0  0.0  1.0           0.0      0.0           0.0   
1   1.0  0.0  1.0  0.0  1.0  0.0           0.0      0.0           0.0   
2   0.0  1.0  0.0  1.0  1.0  0.0           0.0      0.0           0.0   
3   0.0  1.0  0.0  1.0  0.0  1.0           0.0      0.0           0.0   
4   0.0  1.0  1.0  0.0  0.0  1.0           0.0      0.0           0.0   
5   0.0  1.0  0.0  1.0  1.0  0.0           0.0      0.0           0.0   
6   0.0  1.0  0.0  1.0  0.0  1.0           0.0      0.0           0.0   
7   0.0  1.0  0.0  1.0  1.0  0.0           0.0      0.0           0.0   
8   0.0  1.0  1.0  0.0  1.0  0.0           0.0      0.0           0.0   
9   1.0  0.0  1.0  0.0  0.0  1.0           0.0      0.0           0.0   
10  1.0  0.0  0.0  1.0  1.0  0.0           0.0      0.0           0.0   
11  1.0  0.0  0.0  1.0  0.0  1.0           0.0      0.0           0.0   
12  1.0  0.0  1.0  0.0  1.0  0.0           0.0      0.0           0.0   
13  1.0  0.0  0.0  1.0  1.0  0.0           1.0      0.0           0.0   
14  1.0  0.0  1.0  0.0  1.0  0.0           1.0      0.0           0.0   
15  1.0  0.0  1.0  0.0  0.0  1.0           1.0      0.0           0.0   
16  1.0  0.0  0.0  1.0  0.0  1.0           1.0      0.0           0.0   
17  1.0  0.0  1.0  0.0  1.0  0.0           1.0      0.0           0.0   
18  1.0  0.0  0.0  1.0  1.0  0.0           1.0      0.0           0.0   
19  1.0  0.0  0.0  1.0  0.0  1.0           1.0      0.0           0.0   
20  1.0  0.0  1.0  0.0  0.0  1.0           1.0      0.0           0.0   
21  0.0  1.0  0.0  1.0  1.0  0.0           1.0      0.0           0.0   
22  0.0  1.0  1.0  0.0  1.0  0.0           1.0      0.0           0.0   
23  0.0  1.0  1.0  0.0  0.0  1.0           1.0      0.0           0.0   
24  0.0  1.0  0.0  1.0  0.0  1.0           1.0      0.0           0.0   
25  0.0  1.0  1.0  0.0  1.0  0.0           1.0      0.0           0.0   
26  0.0  1.0  0.0  1.0  1.0  0.0           1.0      0.0           0.0   
27  0.0  1.0  0.0  1.0  0.0  1.0           1.0      0.0           0.0   
28  0.0  1.0  1.0  0.0  0.0  1.0           1.0      0.0           0.0   
29  1.0  0.0  1.0  0.0  0.0  1.0           0.0      1.0           0.0   
30  1.0  0.0  1.0  0.0  1.0  0.0           0.0      1.0           0.0   
31  0.0  1.0  1.0  0.0  0.0  1.0           0.0      1.0           0.0   
32  0.0  1.0  0.0  1.0  1.0  0.0           0.0      1.0           0.0   
33  0.0  1.0  0.0  1.0  0.0  1.0           0.0      1.0           0.0   
34  0.0  1.0  1.0  0.0  1.0  0.0           0.0      1.0           0.0   
35  1.0  0.0  1.0  0.0  1.0  0.0           0.0      0.0           1.0   
36  0.0  1.0  0.0  1.0  0.0  1.0           0.0      0.0           1.0   
37  0.0  1.0  0.0  1.0  1.0  0.0           0.0      0.0           1.0   

    raytrace  ...  reads_mod_shared_l3  writes_mod_shared_l3 hw_threads  \
0        1.0  ...            -0.438479             -0.307876        0.0   
1        1.0  ...            -0.264835              0.359078        0.0   
2        1.0  ...             0.246103              2.979554        0.0   
3        1.0  ...            -0.011838              1.763695        0.0   
4        0.0  ...            -0.489985             -0.528429        0.0   
5        0.0  ...            -0.490114             -0.528426        0.0   
6        0.0  ...            -0.490754             -0.528423        0.0   
7        0.0  ...            -0.491557             -0.528615        0.0   
8        0.0  ...            -0.490114             -0.528426        0.0   
9        0.0  ...            -0.489985             -0.528429        0.0   
10       0.0  ...            -0.490114             -0.528426        0.0   
11       0.0  ...            -0.490754             -0.528423        0.0   
12       0.0  ...            -0.490114             -0.528426        0.0   
13       0.0  ...            -0.488012             -0.533870        0.0   
14       0.0  ...            -0

In [42]:
# width

values = array(extract_csv['width'])
print(values)

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(values)
print(integer_encoded)

onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)

alphabetized_values = list(extract_csv['width'].unique())
alphabetized_values.sort()
print(alphabetized_values)

df_program_name = pd.DataFrame(onehot_encoded, columns = alphabetized_values)
df_program_name.head(100)

extract_csv.drop(columns=['width'], inplace=True)

idx = 0
for header in alphabetized_values:
    extract_csv.insert(loc=idx, column=header, value=df_program_name[header])
    idx += 1
    
extract_csv.head(100)

['4' '4' '4' '4' '4' '4' '4' '8' '4' '4' '4' '4' '4' '4' '8' '4' '8' '4'
 '8' '4' '8' '4' '8' '4' '8' '4' '8' '4' '8' '4' '4' '4' '4' '4' '4' '4'
 '4' '4']
[0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0
 0]
[[1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [0. 1.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]
 [1. 0.]]
['4', '8']


4    8  16m  32m   1m   2m  32k  64k  blackscholes  canneal  ...  \
0   1.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0           0.0      0.0  ...   
1   1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0           0.0      0.0  ...   
2   1.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0           0.0      0.0  ...   
3   1.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0           0.0      0.0  ...   
4   1.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0           0.0      0.0  ...   
5   1.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0           0.0      0.0  ...   
6   1.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0           0.0      0.0  ...   
7   0.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0           0.0      0.0  ...   
8   1.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0           0.0      0.0  ...   
9   1.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0           0.0      0.0  ...   
10  1.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0           0.0      0.0  ...   
11  1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0           0.0      0.0  ...   
12  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0           0.0      0.0  ...   
13  1.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0           1.0      0.0  ...   
14  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0           1.0      0.0  ...   
15  1.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0           1.0      0.0  ...   
16  0.0  1.0  1.0  0.0  0.0  1.0  0.0  1.0           1.0      0.0  ...   
17  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0           1.0      0.0  ...   
18  0.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0           1.0      0.0  ...   
19  1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0           1.0      0.0  ...   
20  0.0  1.0  1.0  0.0  1.0  0.0  0.0  1.0           1.0      0.0  ...   
21  1.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0           1.0      0.0  ...   
22  0.0  1.0  0.0  1.0  1.0  0.0  1.0  0.0           1.0      0.0  ...   
23  1.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0           1.0      0.0  ...   
24  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0           1.0      0.0  ...   
25  1.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0           1.0      0.0  ...   
26  0.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0           1.0      0.0  ...   
27  1.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0           1.0      0.0  ...   
28  0.0  1.0  0.0  1.0  1.0  0.0  0.0  1.0           1.0      0.0  ...   
29  1.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0           0.0      1.0  ...   
30  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0           0.0      1.0  ...   
31  1.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0           0.0      1.0  ...   
32  1.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0           0.0      1.0  ...   
33  1.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0           0.0      1.0  ...   
34  1.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0           0.0      1.0  ...   
35  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0           0.0      0.0  ...   
36  1.0  0.0  0.0  1.0  0.0  1.0  0.0  1.0           0.0      0.0  ...   
37  1.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0           0.0      0.0  ...   

    reads_mod_shared_l3  writes_mod_shared_l3  hw_threads       cycles  \
0             -0.438479             -0.307876         0.0   5162965136   
1             -0.264835              0.359078         0.0  13815380707   
2              0.246103              2.979554         0.0  31009448393   
3             -0.011838              1.763695         0.0  24088271698   
4             -0.489985             -0.528429         0.0   1527718090   
5             -0.490114             -0.528426         0.0   1708237934   
6             -0.490754             -0.528423         0.0   1524272911   
7             -0.491557             -0.528615         0.0    940791972   
8             -0.490114             -0.528426         0.0   1708237934   
9             -0.489985             -0.528429         0.0   1527718090   
10            -0.490114             -0.528426         0.0   1708237934   
11            -0.490754             -0.528423         0.0   1524272911   
12            -0.490114             -0.528426         0.0   1708237934   
13            -0.488012             -0.533870         0.0    237325773   
14       

In [43]:
extract_csv.rename(columns={"4": "width_val_4", "8": "width_val_8",
                            "16m": "l3cache_val_16m", "32m": "l3cache_val_32m",
                            "1m": "l2cache_val_1m", "2m": "l2cache_val_2m",
                            "32k": "l1cache_val_32k", "64k": "l1cache_val_64k"
                           }, inplace = True)

In [44]:
extract_csv = extract_csv.drop(columns=['threads','hw_threads'])

In [45]:
extract_csv.to_csv(r'/home/anthony/DS-GA 1006 Capstone/Simulator.csv', index = False, header=True)